---
- name: Assert elasticsearch-role
  hosts: elasticsearch
  roles:
    - elastic-role

- name: Assert filebeat-role
  hosts: filebeat
  roles:
    - filebeat-role

- name: Assert kibana-role
  hosts: kibana
  roles:
    - kibana-role